# Author: HARSH AGARWAL
# SAP ID: 500083087
# ROLL NO: R214220486
# Batch: 5
# Course: Container Orchestration and Infrastructure Automation
# Program: BTECH CSE & Spl. CC&VT


version: '3.8'

services:
  server:
    build:
      context: .
      dockerfile: server/Dockerfile
    container_name: server
    volumes:
      - servervol:/serverdata
    ports:
      - '8081:8081'

  client:
    build:
      context: .
      dockerfile: client/Dockerfile
    container_name: client
    volumes:
      - clientvol:/clientdata
    depends_on:
      - server

volumes:
  servervol:
  clientvol:
